<template>
  <NavigationBar/>
  <div class="privacy">

    <div class="text-white w-3/4 m-auto mt-10">
      <h1 class="font-bold text-5xl mb-5">Policy</h1>
      <p>
        This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the
        law protects You.
      </p>
      <p>
        We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy
        has been created with the help of the Privacy Policy Generator.
      </p>
      <h2 class="text-4xl mt-4">Interpretation and Definitions</h2>
      <h3 class="text-2xl mt-2">Interpretation</h3>
      <p>
        The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear
        in singular or in plural.
      </p>
      <h3 class="text-2xl mt-2">Definitions</h3>
      <p>For the purposes of this Privacy Policy:</p>
      <ul class="list-disc">
        <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
        <li><strong>Company</strong> (referred to as either “the Company”, “We”, “Us” or “Our” in this Agreement) refers to Planfree.</li>
        <li>
          <strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among
          its many uses.
        </li>
        <li><strong>Country</strong> refers to: United Kingdom</li>
        <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
        <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
        <li><strong>Service</strong> refers to the Website.</li>
        <li>
          <strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company
          to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.
        </li>
        <li>
          <strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page
          visit).
        </li>
        <li><strong>Website</strong> refers to Planfree, accessible from https://Planfree.com</li>
        <li>
          <strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as
          applicable.
        </li>
      </ul>
      <h2 class="text-4xl mt-4">Collecting and Using Your Personal Data</h2>
      <h3 class="text-2xl mt-2">Types of Data Collected</h3>
      <h4 class="text-xl mt-1">Personal Data</h4>
      <p>
        While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may
        include, but is not limited to:
      </p>
      <ul class="list-disc">
        <li>Email address</li>
        <li>First name and last name</li>
        <li>Usage Data</li>
      </ul>
      <h4 class="text-xl mt-1">Usage Data</h4>
      <p>
        Usage Data is Cookies can be “Persistent” or “Session” Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as
        soon as You close Your web browser. Learn more about cookies: What Are Cookies?.
      </p>

      <p>We use both Session and Persistent Cookies for the purposes set out below:</p>
      <ul class="list-disc">
        <li>
          <p>
            Necessary / Essential Cookies<br />
            Type: Session Cookies<br />
            Administered by: Us<br />
            Purpose: These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent
            fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.
          </p>
        </li>
        <li>
          <p>
            Cookies Policy / Notice Acceptance Cookies<br />
            Type: Persistent Cookies<br />
            Administered by: Us<br />
            Purpose: These Cookies identify if users have accepted the use of cookies on the Website.
          </p>
        </li>
        <li>
          <p>
            Functionality Cookies<br />
            Type: Persistent Cookies<br />
            Administered by: Us<br />
            Purpose: These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to
            provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.
          </p>
        </li>
      </ul>
      <p>For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.</p>
      <h2 class="text-4xl mt-4">Use of Your Personal Data</h2>
      <p>The Company may use Personal Data for the following purposes:</p>
      <ul class="list-disc">
        <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
        <li>
          To manage Your Account: to manage Your registration as a user of the Service. The Personal Data You provide can give You access to different functionalities of the Service that are available
          to You as a registered user.
        </li>
        <li>
          For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us
          through the Service.
        </li>
        <li>
          To contact You: To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as a mobile application’s push notifications regarding updates or
          informative communications related to the functionalities, products or contracted services, including the security updates, when necessary or reasonable for their implementation.
        </li>
        <li>
          To provide You with news, special offers and general information about other goods, services and events which we offer that are similar to those that you have already purchased or enquired
          about unless You have opted not to receive such information.
        </li>
        <li>To manage Your requests: To attend and manage Your requests to Us.</li>
        <li>
          For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our
          assets, whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal Data held by Us about our Service users is among the assets transferred.
        </li>
        <li>
          For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate
          and improve our Service, products, services, marketing and your experience.
        </li>
      </ul>
      <p>
        We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page. We will let You know via email and/or a prominent notice on
        Our Service, prior to the change becoming effective and update the “Last updated” date at the top of this Privacy Policy. You are advised to review this Privacy Policy periodically for any
        changes. Changes to this Privacy Policy are effective when they are posted on this page.
      </p>
    </div>
  </div>

</template>

<script setup lang="ts">

import NavigationBar from "@/components/NavigationBar.vue";
</script>

<style scoped lang="scss">
.privacy {
  margin: 10px;
  display: flex;
  justify-content: center;
  align-items: center;
  width: 60%;
  text-align: left;
  position: absolute;
  left: 50%;
  transform: translate(-50%, 0%);
  line-height: 30px;
}

</style>